---
- hosts: all
  tasks:
    - yum:
        name={{ item }}
        state=absent
      with_items:
        - graphite-web
        - python-memcached
        - python-whisper
        - python-carbon
        - python-ldap
        - httpd
        - memcached
        - haproxy
        - carbonate
        - diamond
        - mysql-server
        - mysql
        - MySQL-python

    - file:
        path={{ item }}
        state=absent
      with_items:
        - /etc/yum.repos.d/pfc.repo
        - /etc/motd

    - command: /bin/rm -rf {{ item }}
      with_items:
        - /var/lib/mysql
        - /var/lib/carbon

    - user:
        name={{ item }}
        state=absent
        remove=yes
      with_items:
        - carbon
        - httpd
        - mysql
