---
- hosts: all
  tasks:
    - yum:
        name={{ item }}
        state=absent
      with_items:
        - graphite-web
        - python-memcached
        - python-whisper
        - python-carbon
        - python-ldap
        - httpd
        - memcached
        - haproxy
        - diamond

    - command: /bin/rm /etc/motd

    - file:
        path=/etc/yum.repos.d/pfc.repo
        state=absent
