---
- name: reiniciar apache
  service:
    name=httpd
    state=restarted

- name: reiniciar carbon
  service:
    name={{ item }}
    state=restarted
  with_items:
    - carbon-cache
    - carbon-relay
    - carbon-aggregator

- name: reiniciar memcached
  service:
    name=memcached
    state=restarted

- name: borrar metricas incorrectas
  command: /usr/bin/graphite-purge.sh {{ ansible_ssh_host }}
