---
- name: Instalando paquetes LB
  yum:
    name={{ item }}
    disablerepo=*
    enablerepo=pfc-repo
    state=latest
  with_items: lb_pkgs

- name: Configurando mysql-server
  template:
    src=my.cnf.j2
    dest=/etc/my.cnf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar mysqld

- name: Arrancando MySQLd
  service:
    name=mysqld
    state=started
    enabled=true

- name: Contrase침a de root
  mysql_user:
    name=root
    password={{ db_root_pass }}
    priv=*.*:ALL,GRANT
  ignore_erros: true

- name: Eliminando base de datos de test
  mysql_db:
    login_user=root
    login_password={{ db_root_pass }}
    db=test
    state=absent

- name: Creando base de datos Graphite
  mysql_db:
    login_user=root
    login_password={{ db_root_pass }}
    db={{ db_name }}
    state=present
    collation=utf8_general_ci
    encoding=utf8

- name: Creaci칩n de usuario graphite
  mysql_user:
    login_user=root
    login_password={{ db_root_pass }}
    name={{ db_user }}
    password={{ db_password }}
    priv={{ db_name }}.*:ALL

- name: Configurando Memcached
  template:
    src=memcached.conf.j2
    dest=/etc/sysconfig/memcached
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar memcached

- name: Aplicando configuraci칩n local_settings.py
  template:
    src=local_settings.py.j2
    dest=/etc/graphite-web/local_settings.py
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar apache

- name: Aplicando configuraci칩n virtualhost
  copy:
    src=graphite-web.conf.j2
    dest=/etc/httpd/conf.d/graphite-web.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar apache

- name: Verificando base de datos
  django_manage:
    app_path=/usr/lib/python2.6/site-packages/graphite/
    command=syncdb

- name: configurando carbon-relay
  template:
    src=carbon.conf.j2
    dest=/etc/carbon/carbon.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar carbon-relay

- name: Configurando haproxy
  template:
    src=haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar haproxy

- name: Chequeando servicios LB
  service:
    name={{ item }}
    state=started
    enabled=yes
  with_items:
    - carbon-relay
    - mysqld
    - memcached
    - httpd
