---
- name: Instalando paquetes de Graphite
  yum:
    name={{ item }}
    disablerepo=*
    enablerepo=pfc-repo
    state=latest
  with_items: graphite_pkgs

- name: Aplicando configuración /etc/carbon/carbon.conf
  template:
    src=carbon.conf.j2
    dest=/etc/carbon/carbon.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar carbon

- name: Configurando Memcached
  template:
    src=memcached.conf.j2
    dest=/etc/sysconfig/memcached
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar memcached

- name: Aplicando configuración local_settings.py
  template:
    src=local_settings.py.j2
    dest=/etc/graphite-web/local_settings.py
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar apache

- name: Aplicando configuración virtualhost
  copy:
    src=graphite-web.conf
    dest=/etc/httpd/conf.d/graphite-web.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar apache

- name: Verificando base de datos
  django_manage:
    app_path=/usr/lib/python2.6/site-packages/graphite/
    command=syncdb

- name: Chequeando permisos
  file:
    path=/var/lib/graphite-web/graphite.db
    owner=apache
    group=apache
    mode=0644

- name: Comprobando scripts de arranque
  copy:
    src=carbon-cache
    dest=/etc/init.d/carbon-cache
    owner=root
    group=root
    mode=0755
    backup=yes

- name: Chequeando servicios Graphite
  service:
    name={{ item }}
    enabled=yes
    state=started
  with_items:
    - carbon-cache
    - carbon-relay
    - memcached
    - httpd
