---
- name: Instalando paquetes de Graphite
  yum:
    name={{ item }}
    disablerepo=*
    enablerepo=pfc-repo
    state=latest
  with_items: graphite_pkgs
  register: paquetes

- name: Copiando scripts de mantenimiento del cluster
  copy:
    src=scripts/{{ item }}
    dest=/usr/bin/{{ item }}
    mode=0755
    owner=root
    group=root
  with_items:
    - graphite-rebalance.sh
    - graphite-sync.sh
    - graphite-purge.sh

- name: Configurando usuario Carbon
  user:
    name=carbon
    shell=/bin/bash

- name: Preparando directorio Carbon
  file:
    dest=/var/lib/carbon/.ssh
    state=directory
    mode=0700
  become_user: carbon

- name: Copiando claves para el usuario Carbon
  copy:
    src=carbon_keys/carbon_id_rsa
    dest=/var/lib/carbon/.ssh/id_rsa
    mode=0600
  become_user: carbon

- name: Autorizando claves publicas
  authorized_key:
    user=carbon
    key="{{ lookup('file', 'carbon_keys/carbon_id_rsa.pub') }}"
    state=present

- name: Aplicando configuración /etc/carbon/carbon.conf
  template:
    src=carbon.conf.j2
    dest=/etc/carbon/carbon.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar carbon

- name: Configurando Memcached
  template:
    src=memcached.conf.j2
    dest=/etc/sysconfig/memcached
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar memcached

- name: Aplicando configuración local_settings.py
  template:
    src=local_settings.py.j2
    dest=/etc/graphite-web/local_settings.py
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar apache

- name: Aplicando configuración virtualhost
  copy:
    src=graphite-web.conf
    dest=/etc/httpd/conf.d/graphite-web.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: reiniciar apache

- name: Configurando carbonate.conf
  template:
    src=carbonate.conf.j2
    dest=/etc/carbonate.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  register: nuevaconf

- name: Ruta de logs para carbonate
  file:
    path=/var/log/carbonate
    owner=carbon
    group=carbon
    state=directory

- name: Resincronizando nodo
  shell: /usr/bin/graphite-sync.sh {{ ansible_ssh_host }} >> /var/log/carbonate/graphite-sync.log
  become_user: carbon
  when: paquetes.changed
  notify: borrar metricas incorrectas

- name: Balanceando cluster
  shell: /usr/bin/graphite-rebalance.sh {{ ansible_ssh_host }} {{ nuevaconf.backup_file | quote }} >> /var/log/carbonate/graphite-rebalance.log
  become_user: carbon
  when: nuevaconf.backup_file is defined
  notify: borrar metricas incorrectas

- name: Verificando base de datos
  django_manage:
    app_path=/usr/lib/python2.6/site-packages/graphite/
    command=syncdb

- name: Chequeando permisos
  file:
    path=/var/lib/graphite-web/graphite.db
    owner=apache
    group=apache
    mode=0644

- name: Comprobando scripts de arranque
  copy:
    src=carbon-cache
    dest=/etc/init.d/carbon-cache
    owner=root
    group=root
    mode=0755
    backup=yes

- name: Chequeando servicios Graphite
  service:
    name={{ item }}
    enabled=yes
    state=started
  with_items:
    - carbon-cache
    - carbon-relay
    - memcached
    - httpd
